# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_field', models.IntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('master_branch', models.TextField(blank=True, null=True)),
                ('clone_url', models.TextField(blank=True, null=True, unique=True)),
                ('cloned_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repositories',
                'managed': False,
            },
        ),
    ]
