# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_tagger_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repositories',
            table=None,
        ),
    ]
