# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_tagger_app', '0002_auto_20160612_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('repository_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('extracted_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('deletion_commit_hash', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedComments',
            fields=[
                ('id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False, unique=True)),
                ('repository_id', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('file_versions_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('commit_hash', models.TextField(blank=True, null=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('treated_comment_text', models.TextField(blank=True, null=True)),
                ('td_classification', models.TextField(blank=True, null=True)),
                ('comment_type', models.TextField(blank=True, null=True)),
                ('comment_format', models.TextField(blank=True, null=True)),
                ('start_line', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('end_line', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('has_class_declaration', models.NullBooleanField()),
                ('has_interface_declaration', models.NullBooleanField()),
                ('has_enum_declaration', models.NullBooleanField()),
                ('has_annotation_declaration', models.NullBooleanField()),
                ('class_declaration_lines', models.TextField(blank=True, null=True)),
                ('introduced_version_commit_hash', models.TextField(blank=True, null=True)),
                ('is_introduced_version', models.NullBooleanField()),
                ('introduced_version_author', models.TextField(blank=True, null=True)),
                ('introduced_version_date', models.DateTimeField(blank=True, null=True)),
                ('removed_version_commit_hash', models.TextField(blank=True, null=True)),
                ('has_removed_version', models.NullBooleanField()),
                ('removed_version_author', models.TextField(blank=True, null=True)),
                ('removed_version_date', models.DateTimeField(blank=True, null=True)),
                ('interval_time_to_remove', models.TextField(blank=True, null=True)),
                ('comment_location', models.TextField(blank=True, null=True)),
                ('func_specifier', models.TextField(blank=True, null=True)),
                ('func_return_type', models.TextField(blank=True, null=True)),
                ('func_name', models.TextField(blank=True, null=True)),
                ('func_parameter_list', models.TextField(blank=True, null=True)),
                ('func_line', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('epoch_time_to_remove', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'processed_comments',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='repositories',
            table='repositories',
        ),
    ]
